### PR TITLE
Changed the endpoint to a more conventional RESTFul endpoint

### PR DESCRIPTION
**Pull request by chisomd90**
​
## Description
I followed the REST API URI Naming Conventions to rename the delete_wishlist endpoint
​
## Related Issue (Link to linear ticket)

​
## Motivation and Context

​
## How Has This Been Tested?

​
## Screenshots (if appropriate - Postman, etc):
​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by johndiginee — COMMENTED** [review]
Hope you informed our frontend dev regarding these changes.

**Review by phurhard — APPROVED** [review]
Done

**Comment by phurhard** [comment]
Inform them now

**Comment by chisomd90** [comment]
ok

**Pull request closed without merging**
