### PR TITLE
Task/BugFix/Wishlist-Empty-Response

### PR DESCRIPTION
**Pull request by iamprecieee**
## Description

- Updated the endpoint to return an empty list when a wishlist is not found, and display corresponding error message.

​
## Related Issue (Link to linear ticket)
​
## Motivation and Context

-  Need for a more restful api.
​
## How Has This Been Tested?
​
## Screenshots (if appropriate - Postman, etc):

- [Screenshot](https://drive.google.com/file/d/1ZbBWbnnm-V_ALyHv3eRx3ySX18M-UvDX/view?usp=sharing)

​
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by johndiginee** [comment]
Please, Fix the stuff, pull, and push your code 'cause we updated the settings.py file. Thank you

**Comment by iamprecieee** [comment]
Okay

**Review by iamprecieee — COMMENTED** [review]
updated

**Review by johndiginee — APPROVED** [review]
Thank you

**Pull request merged**
