### PR TITLE
Mar 52/bug fix/test case

### PR DESCRIPTION
**Pull request by nielsen2e**
## Description

**1. Imported DRF's status:**
This provides more clarity about the HTTP status codes being checked.

**2. Added a helper function get_search_url:**
This function constructs the URL with the query parameters to reduce code repetition and improve readability.

**3. Used the get_search_url function in tests:**
This change makes the tests more concise and avoids hardcoding the query parameters multiple times.

​
## Related Issue (Link to linear ticket)
​
## Motivation and Context

**1. Clarity:** 
Using clear names and structures helps tests serve as effective documentation for developers, showcasing the test's purpose.

**2. Maintainability:**
 Reducing repetition and using helper functions mean tests are easier to update, promoting adaptability with future changes.

**3. Scalability:** 
Helper functions, like constructing URLs, are extensible and can be adapted for future complexities without major rewrites.
In essence, the modifications ensure the tests are clear, easily maintainable, and scalable to accommodate project evolution.

## How Has This Been Tested?
​
## Screenshots (if appropriate - Postman, etc):
​
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by phurhard** [comment]
Send a message to the channel now, informing the FE consuming the endpoint that you are paginating from the server

**Comment by nielsen2e** [comment]
already did

**Comment by phurhard** [comment]
Sorry bro, buh please do a repull n push

**Comment by nielsen2e** [comment]
I can't mhen,  my laptop is dead

**Comment by phurhard** [comment]
Submit, i have done it

**Pull request merged**
